[server]
enableCORS = false

[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[setup]
tensorboardRequiredArgs = []

[global]
developmentMode = false

[serialization]
useGlobally = true 